services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php
    networks:
      - working-management-network

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    networks:
      - working-management-network

  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: working_management_db
      MYSQL_USER: working_user
      MYSQL_PASSWORD: working_pass
    command:
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - working-management-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=working_user
      - PMA_PASSWORD=working_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - working-management-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - working-management-network

networks:
  working-management-network:
    driver: bridge